import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientWrapper from "./components/ClientWrapper"; // Import your ClientWrapper component
import { MyProvider } from './context/CreditContex'; 
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Behrupiya.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientWrapper>
          <MyProvider>
          {children}
          </MyProvider>
     </ClientWrapper>
      </body>
    </html>
  );
}
